version: "3"
services:
    mongodb:
        image: mongo:4.0.10
        container_name: "klickly-mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ../../_services-data/mongodb:/data/db
        ports:
            - "27018:27017"

networks:
    default:
        external:
            name: klickly-network
